            - name: Archethic Web
  # You may pin to the exact commit or the version.
  # uses: archethic-foundation/aeweb-github-action@53c0083a5bf3f14b6486f2a11167f13fb08cf519
  uses: archethic-foundation/aeweb-github-action@v1.8.9
  with:
    # Seed of the transaction chain
    seed: 
    # Endpoint of the network, default is https://testnet.archethic.net
    endpoint: # default is https://testnet.archethic.net
    # Path of the folder/file/website, default ./
    path: # default is ./
    # Keychain's service to funds the website transactions
    keychainFundingService: # optional
    # Keychain's service for the deployed website
    keychainWebsiteService: # optional
    # File for the website's SSL certificate
    sslCertificateFile: # optional
    # Website's SSL key
    sslKey: # optional
    # Timeout for the send_transaction query (default=60000)
    sendTransactionTimeout: # optional
    # 1-100 % of the confirmations success to mark the transaction as valid (default=50)
    percentageOfConfirmations: # optional
          
